-- comment

CREATE TABLE IF NOT EXISTS bookkeeping (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    payment_name TEXT NOT NULL,
    price REAL NOT NULL DEFAULT 0,
    amount REAL NOT NULL DEFAULT 1,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
